name: Skuishy
version: '${version}'
main: lol.aabss.skuishy.Skuishy
api-version: '1.17'
depend:
  - Skript
softdepend:
  - DecentHolograms
  - Vivecraft-Spigot-Extensions
  - Vulcan
authors: [aabss]
description: yet another skript addon
contributors:
  - Fusezion
  - CoffeeRequired
website: https://aabss.lol
commands:
  skuishy:
    description: The main command for Skuishy.