name: Skuishy
version: '${version}'
main: lol.aabss.skuishy.Skuishy
api-version: '1.17'
depend:
  - Skript
softdepend:
  - ProtocolLib
  - DecentHolograms
authors: [aabss]
website: https://aabss.lol
commands:
  skuishy: