name: Build & Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew clean shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skuishy
          path: build/libs/*.jar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Skuishy
          path: build/libs
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.0
        with:
          test_script_directory: src/test/resources
          skript_repo_ref: master
          extra_plugins_directory: extra-plugins/
