name: Build & Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - uses: actions/upload-artifact@v4
      with:
        name: skuishy
        path: build/libs/*.jar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Skuishy
          path: build/libs
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.0
        with:
          test_script_directory: src/test/resources
          skript_repo_ref: master
          extra_plugins_directory: extra-plugins/
